---
- name: Routing and Device Info Configuration (Part B)
  hosts: routers
  gather_facts: no
  tasks:
    - name: Configure interface description
      cisco.ios.ios_config:
        lines:
          - description Connection to Main Office LAN
        parents: interface GigabitEthernet1
    - name: Configure static route
      cisco.ios.ios_config:
        lines:
          - ip route 10.10.10.0 255.255.255.0 192.168.1.254
